/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { RangeRequestsPlugin } from 'workbox-range-requests';

declare const self: ServiceWorkerGlobalScope & { __WB_MANIFEST: any };

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old caches
cleanupOutdatedCaches();

// Manually cache the full PMTiles file on install to ensure RangeRequestsPlugin has a 200 OK full file to slice
self.addEventListener('install', (event) => {
  event.waitUntil(
    Promise.all([
      caches.open('pmtiles-cache').then((cache) => {
        // Fetch the full file and cache it, but catch errors so SW install doesn't fail
        return cache.add('/maps/tuzla.pmtiles').catch((err) => {
          console.warn('Failed to cache pmtiles on install:', err);
        });
      }),
      caches.open('local-data').then((cache) => {
        return cache.addAll([
          '/maps/TuzlaTourGuide.geojson',
          '/style/offline-style.json',
          '/poi.geojson',
          '/maps/buildings.geojson'
        ]).catch((err) => console.warn('Failed to cache core map data on install:', err));
      })
    ])
  );
});

// 1. Google Fonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [
      new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 365 * 24 * 60 * 60 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

// 2. Local Map Tiles (CRITICAL for Offline Map)
registerRoute(
  ({ url }) => url.pathname.startsWith('/maps/tiles/'),
  new CacheFirst({
    cacheName: 'local-map-tiles',
    plugins: [
      new ExpirationPlugin({ maxEntries: 2000, maxAgeSeconds: 30 * 24 * 60 * 60 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

// 2.5 PMTiles (Protomaps Vector tiles) - CRITICAL for Offline PMTiles
registerRoute(
  ({ url }) => url.pathname.includes('tuzla.pmtiles'),
  new CacheFirst({
    cacheName: 'pmtiles-cache',
    plugins: [
      new RangeRequestsPlugin(),
      new CacheableResponsePlugin({ statuses: [200, 206] }),
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 365 * 24 * 60 * 60 }),
    ],
  })
);

// 3. Local Data & Styles (GeoJSON, JSON)
registerRoute(
  ({ url }) => url.pathname.endsWith('.geojson') || url.pathname.includes('/style/') || url.pathname.endsWith('.json'),
  new StaleWhileRevalidate({
    cacheName: 'local-data',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

// 4. External Map Styles/Assets (Geoapify, Jawg, OSM, etc.)
registerRoute(
  ({ url }) => 
    url.origin.includes('api.jawg.io') || 
    url.origin.includes('tile.openstreetmap.org') ||
    url.origin.includes('maps.geoapify.com') ||
    url.origin.includes('api.geoapify.com'),
  new StaleWhileRevalidate({
    cacheName: 'external-map-assets',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

// 6. Images (JPG, PNG, WEBP, SVG)
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 30 * 24 * 60 * 60 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

// 5. Videos (MP4, WEBM) - Use RangeRequests for partial content
registerRoute(
  ({ request }) => request.destination === 'video',
  new CacheFirst({
    cacheName: 'videos',
    plugins: [
      new RangeRequestsPlugin(),
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 7 * 24 * 60 * 60 }),
      new CacheableResponsePlugin({ statuses: [200, 206] }),
    ],
  })
);

// 7. Navigation Route (SPA Support)
// Serve precached index.html instantly for all navigation requests
try {
  registerRoute(
    new NavigationRoute(createHandlerBoundToURL('/index.html'))
  );
} catch (error) {
  // Fallback in case index.html is not in the precache manifest
  registerRoute(
    new NavigationRoute(
      new NetworkFirst({
        cacheName: 'pages',
        plugins: [
          new CacheableResponsePlugin({ statuses: [200] }),
        ],
      })
    )
  );
}

// Handle skipWaiting
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
